//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Contractor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contractor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Contractor", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string chactive {
            get {
                return ResourceManager.GetString("chactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contractor.
        /// </summary>
        internal static string lbAddcontractor {
            get {
                return ResourceManager.GetString("lbAddcontractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contractor.
        /// </summary>
        internal static string lbAddcontractor1 {
            get {
                return ResourceManager.GetString("lbAddcontractor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string lbcompany {
            get {
                return ResourceManager.GetString("lbcompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        internal static string lbcompanyen {
            get {
                return ResourceManager.GetString("lbcompanyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor detail.
        /// </summary>
        internal static string lbDetailcontractor {
            get {
                return ResourceManager.GetString("lbDetailcontractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lbemail {
            get {
                return ResourceManager.GetString("lbemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name (EN).
        /// </summary>
        internal static string lbfirstnameen {
            get {
                return ResourceManager.GetString("lbfirstnameen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        internal static string lbformheader {
            get {
                return ResourceManager.GetString("lbformheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        internal static string lbformheader1 {
            get {
                return ResourceManager.GetString("lbformheader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name (TH).
        /// </summary>
        internal static string lbfristnameth {
            get {
                return ResourceManager.GetString("lbfristnameth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name Contractor.
        /// </summary>
        internal static string lbfullname {
            get {
                return ResourceManager.GetString("lbfullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string lbfunction {
            get {
                return ResourceManager.GetString("lbfunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string lbfunction1 {
            get {
                return ResourceManager.GetString("lbfunction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name (EN).
        /// </summary>
        internal static string lblastnameen {
            get {
                return ResourceManager.GetString("lblastnameen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name (EN).
        /// </summary>
        internal static string lblastnameth {
            get {
                return ResourceManager.GetString("lblastnameth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone.
        /// </summary>
        internal static string lbmobilephone {
            get {
                return ResourceManager.GetString("lbmobilephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By : .
        /// </summary>
        internal static string lbModify {
            get {
                return ResourceManager.GetString("lbModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string lbno {
            get {
                return ResourceManager.GetString("lbno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string lbphone {
            get {
                return ResourceManager.GetString("lbphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix (EN).
        /// </summary>
        internal static string lbprefixen {
            get {
                return ResourceManager.GetString("lbprefixen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix (TH).
        /// </summary>
        internal static string lbprefixth {
            get {
                return ResourceManager.GetString("lbprefixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lbstatus {
            get {
                return ResourceManager.GetString("lbstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date : .
        /// </summary>
        internal static string lbUpdate {
            get {
                return ResourceManager.GetString("lbUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name  field is required..
        /// </summary>
        internal static string rqcomapany {
            get {
                return ResourceManager.GetString("rqcomapany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company no more than 100 characters..
        /// </summary>
        internal static string rqcompanylength {
            get {
                return ResourceManager.GetString("rqcompanylength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function field is required..
        /// </summary>
        internal static string rqddlfunction {
            get {
                return ResourceManager.GetString("rqddlfunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix (EN) field is required..
        /// </summary>
        internal static string rqddlprefixen {
            get {
                return ResourceManager.GetString("rqddlprefixen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix (TH)  field is required..
        /// </summary>
        internal static string rqddlprefixth {
            get {
                return ResourceManager.GetString("rqddlprefixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email field is required..
        /// </summary>
        internal static string rqemail {
            get {
                return ResourceManager.GetString("rqemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate email..
        /// </summary>
        internal static string rqemailDuplicate {
            get {
                return ResourceManager.GetString("rqemailDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email..
        /// </summary>
        internal static string rqemailExpression {
            get {
                return ResourceManager.GetString("rqemailExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name (EN)  field is required..
        /// </summary>
        internal static string rqfirstnameen {
            get {
                return ResourceManager.GetString("rqfirstnameen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name (TH)  field is required..
        /// </summary>
        internal static string rqfirstnameth {
            get {
                return ResourceManager.GetString("rqfirstnameth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name (EN)  field is required..
        /// </summary>
        internal static string rqlastnameen {
            get {
                return ResourceManager.GetString("rqlastnameen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name (TH)  field is required..
        /// </summary>
        internal static string rqlastnameth {
            get {
                return ResourceManager.GetString("rqlastnameth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mobile phone..
        /// </summary>
        internal static string rqmobileformphone {
            get {
                return ResourceManager.GetString("rqmobileformphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone field is reqired..
        /// </summary>
        internal static string rqmobilephone {
            get {
                return ResourceManager.GetString("rqmobilephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone no more than 12 characters..
        /// </summary>
        internal static string rqmobilephonelength {
            get {
                return ResourceManager.GetString("rqmobilephonelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number field is reqired..
        /// </summary>
        internal static string rqphone {
            get {
                return ResourceManager.GetString("rqphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number no more than 50 characters..
        /// </summary>
        internal static string rqphonelength {
            get {
                return ResourceManager.GetString("rqphonelength", resourceCulture);
            }
        }
    }
}
