//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Health {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Health() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Health", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Health Check Report.
        /// </summary>
        internal static string add_occupational_health {
            get {
                return ResourceManager.GetString("add_occupational_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Health Rehabilitation Action.
        /// </summary>
        internal static string add_process_action {
            get {
                return ResourceManager.GetString("add_process_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Risk Factor Related Work.
        /// </summary>
        internal static string add_risk_factor_relate_work {
            get {
                return ResourceManager.GetString("add_risk_factor_relate_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Health Rehabilitation.
        /// </summary>
        internal static string all_health_header {
            get {
                return ResourceManager.GetString("all_health_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string approval {
            get {
                return ResourceManager.GetString("approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        internal static string attachment {
            get {
                return ResourceManager.GetString("attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment (Can upload only  1 file (JPG, PNG,PDF,DOCX)  and max file size is 5 MB).
        /// </summary>
        internal static string attachment_header {
            get {
                return ResourceManager.GetString("attachment_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btHealthedit {
            get {
                return ResourceManager.GetString("btHealthedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to Close Health Rehabilitation.
        /// </summary>
        internal static string btRequestclose {
            get {
                return ResourceManager.GetString("btRequestclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Report.
        /// </summary>
        internal static string btSubmitReport {
            get {
                return ResourceManager.GetString("btSubmitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Action.
        /// </summary>
        internal static string close_action {
            get {
                return ResourceManager.GetString("close_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comply.
        /// </summary>
        internal static string comply {
            get {
                return ResourceManager.GetString("comply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider for approval field is reqired..
        /// </summary>
        internal static string consider_approval {
            get {
                return ResourceManager.GetString("consider_approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Complete.
        /// </summary>
        internal static string date_complete {
            get {
                return ResourceManager.GetString("date_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string detailreject {
            get {
                return ResourceManager.GetString("detailreject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health No..
        /// </summary>
        internal static string doc_no {
            get {
                return ResourceManager.GetString("doc_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        internal static string due_date {
            get {
                return ResourceManager.GetString("due_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of Risk Exposure per Day.
        /// </summary>
        internal static string duration_risk_factor {
            get {
                return ResourceManager.GetString("duration_risk_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Action Attachment.
        /// </summary>
        internal static string file_action_close {
            get {
                return ResourceManager.GetString("file_action_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check Attachment.
        /// </summary>
        internal static string file_health_check {
            get {
                return ResourceManager.GetString("file_health_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Opinion Attachment.
        /// </summary>
        internal static string file_opinion_doctor {
            get {
                return ResourceManager.GetString("file_opinion_doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rehabilitation Plan Attachment.
        /// </summary>
        internal static string file_recovery_plan {
            get {
                return ResourceManager.GetString("file_recovery_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated Health Check Attachment.
        /// </summary>
        internal static string file_repeat_result_health {
            get {
                return ResourceManager.GetString("file_repeat_result_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check Attachment.
        /// </summary>
        internal static string file_result_health {
            get {
                return ResourceManager.GetString("file_result_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of Environmental Inspection Attachment.
        /// </summary>
        internal static string file_risk_factor {
            get {
                return ResourceManager.GetString("file_risk_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated Health Check Attachment.
        /// </summary>
        internal static string flie_repeat_health_check {
            get {
                return ResourceManager.GetString("flie_repeat_health_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated Health Check.
        /// </summary>
        internal static string have_repeat_health_check {
            get {
                return ResourceManager.GetString("have_repeat_health_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Rehabilitation Report.
        /// </summary>
        internal static string healthstep1 {
            get {
                return ResourceManager.GetString("healthstep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Rehabilitation Action.
        /// </summary>
        internal static string healthstep2 {
            get {
                return ResourceManager.GetString("healthstep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to Close Health Rehabilitation Report.
        /// </summary>
        internal static string healthstep3 {
            get {
                return ResourceManager.GetString("healthstep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string hour_risk_factor {
            get {
                return ResourceManager.GetString("hour_risk_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Can upload up to 2 files (only PDF, JPG, and PNG) and maximum 10 MB all files.).
        /// </summary>
        internal static string infooccuimage {
            get {
                return ResourceManager.GetString("infooccuimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Can upload up to 3 files (only PDF, JPG, and PNG) and maximum 10 MB all files.).
        /// </summary>
        internal static string inforiskimage {
            get {
                return ResourceManager.GetString("inforiskimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insignificant risk factor related work.
        /// </summary>
        internal static string insignificant {
            get {
                return ResourceManager.GetString("insignificant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal.
        /// </summary>
        internal static string lbabnormal {
            get {
                return ResourceManager.GetString("lbabnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal audiogram.
        /// </summary>
        internal static string lbabnormalaudiogram {
            get {
                return ResourceManager.GetString("lbabnormalaudiogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal Health Check Report.
        /// </summary>
        internal static string lbabnormal_health_check_report {
            get {
                return ResourceManager.GetString("lbabnormal_health_check_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal pulmonary function.
        /// </summary>
        internal static string lbabnormal_pulmonary_function {
            get {
                return ResourceManager.GetString("lbabnormal_pulmonary_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string lbage {
            get {
                return ResourceManager.GetString("lbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audiogram.
        /// </summary>
        internal static string lbaudiogram {
            get {
                return ResourceManager.GetString("lbaudiogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        internal static string lbboth_ear {
            get {
                return ResourceManager.GetString("lbboth_ear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any personal health problem or chronic diseases in the ears?.
        /// </summary>
        internal static string lbchronic_diseases_ear {
            get {
                return ResourceManager.GetString("lbchronic_diseases_ear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cigarette(s) per day.
        /// </summary>
        internal static string lbcigarettes_per_day {
            get {
                return ResourceManager.GetString("lbcigarettes_per_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string lbCompany {
            get {
                return ResourceManager.GetString("lbCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company of reporter.
        /// </summary>
        internal static string lbcompany_reporter {
            get {
                return ResourceManager.GetString("lbcompany_reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string lbdateofbirth {
            get {
                return ResourceManager.GetString("lbdateofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant/Department.
        /// </summary>
        internal static string lbdepartment {
            get {
                return ResourceManager.GetString("lbdepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of reporter.
        /// </summary>
        internal static string lbdepartment_reporter {
            get {
                return ResourceManager.GetString("lbdepartment_reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string lbdivision {
            get {
                return ResourceManager.GetString("lbdivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        internal static string lbemployeeid {
            get {
                return ResourceManager.GetString("lbemployeeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        internal static string lbemployee_name {
            get {
                return ResourceManager.GetString("lbemployee_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment report.
        /// </summary>
        internal static string lbenvironment_report {
            get {
                return ResourceManager.GetString("lbenvironment_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function/Business Unit.
        /// </summary>
        internal static string lbfucntion {
            get {
                return ResourceManager.GetString("lbfucntion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function of reporter.
        /// </summary>
        internal static string lbfunction_reporter {
            get {
                return ResourceManager.GetString("lbfunction_reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Rehabilitation No..
        /// </summary>
        internal static string lbhealthno {
            get {
                return ResourceManager.GetString("lbhealthno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check.
        /// </summary>
        internal static string lbhealth_check {
            get {
                return ResourceManager.GetString("lbhealth_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check Report due to Risk Factor Related Work.
        /// </summary>
        internal static string lbhealth_check_report {
            get {
                return ResourceManager.GetString("lbhealth_check_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check up hospital.
        /// </summary>
        internal static string lbhealth_check_up_hospital {
            get {
                return ResourceManager.GetString("lbhealth_check_up_hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Rehabilitation.
        /// </summary>
        internal static string lbhealth_rehab {
            get {
                return ResourceManager.GetString("lbhealth_rehab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Rehabilitation Individual Report.
        /// </summary>
        internal static string lbhealth_rehabilitation_individual_report {
            get {
                return ResourceManager.GetString("lbhealth_rehabilitation_individual_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearing threshold level.
        /// </summary>
        internal static string lbhearing_threshold_level {
            get {
                return ResourceManager.GetString("lbhearing_threshold_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiring date.
        /// </summary>
        internal static string lbhiringdate {
            get {
                return ResourceManager.GetString("lbhiringdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check-Up Hospital.
        /// </summary>
        internal static string lbhospital {
            get {
                return ResourceManager.GetString("lbhospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imbalance of body chemistry.
        /// </summary>
        internal static string lbimbalance_body_chemistry {
            get {
                return ResourceManager.GetString("lbimbalance_body_chemistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Description / Machine Type.
        /// </summary>
        internal static string lbjobtype {
            get {
                return ResourceManager.GetString("lbjobtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left ear.
        /// </summary>
        internal static string lbleft_ear {
            get {
                return ResourceManager.GetString("lbleft_ear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string lbmonth {
            get {
                return ResourceManager.GetString("lbmonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string lbmonths {
            get {
                return ResourceManager.GetString("lbmonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of reporter.
        /// </summary>
        internal static string lbNameReportHeader {
            get {
                return ResourceManager.GetString("lbNameReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string lbno {
            get {
                return ResourceManager.GetString("lbno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obstructive.
        /// </summary>
        internal static string lbobstructive {
            get {
                return ResourceManager.GetString("lbobstructive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obstructive and Restrictive.
        /// </summary>
        internal static string lbobstructive_restrictive {
            get {
                return ResourceManager.GetString("lbobstructive_restrictive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to occupational vision.
        /// </summary>
        internal static string lboccupational_vision {
            get {
                return ResourceManager.GetString("lboccupational_vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal health problem or Chronic diseases in the ear.
        /// </summary>
        internal static string lbpersonal_health_problem {
            get {
                return ResourceManager.GetString("lbpersonal_health_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string lbprofile {
            get {
                return ResourceManager.GetString("lbprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pulmonary function.
        /// </summary>
        internal static string lbpulmonary_function {
            get {
                return ResourceManager.GetString("lbpulmonary_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for reject report.
        /// </summary>
        internal static string lbreasonreject {
            get {
                return ResourceManager.GetString("lbreasonreject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictive.
        /// </summary>
        internal static string lbrestrictive {
            get {
                return ResourceManager.GetString("lbrestrictive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right ear.
        /// </summary>
        internal static string lbright_ear {
            get {
                return ResourceManager.GetString("lbright_ear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string lbsection {
            get {
                return ResourceManager.GetString("lbsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service year.
        /// </summary>
        internal static string lbserviceyear {
            get {
                return ResourceManager.GetString("lbserviceyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Year in Current Position.
        /// </summary>
        internal static string lbserviceyear_current {
            get {
                return ResourceManager.GetString("lbserviceyear_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you ever smoked a cigarettes ?.
        /// </summary>
        internal static string lbsmoked_cigarettes {
            get {
                return ResourceManager.GetString("lbsmoked_cigarettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string lbsmoked_other {
            get {
                return ResourceManager.GetString("lbsmoked_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking Record.
        /// </summary>
        internal static string lbsmoking_record {
            get {
                return ResourceManager.GetString("lbsmoking_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify.
        /// </summary>
        internal static string lbspecify_chronic_diseases_ear {
            get {
                return ResourceManager.GetString("lbspecify_chronic_diseases_ear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lbstatus {
            get {
                return ResourceManager.GetString("lbstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working background.
        /// </summary>
        internal static string lbworking_background {
            get {
                return ResourceManager.GetString("lbworking_background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of Health Checkup.
        /// </summary>
        internal static string lbyear {
            get {
                return ResourceManager.GetString("lbyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        internal static string lbyears {
            get {
                return ResourceManager.GetString("lbyears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string lbyear_check {
            get {
                return ResourceManager.GetString("lbyear_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string lbyes {
            get {
                return ResourceManager.GetString("lbyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, but quit. I smoked for.
        /// </summary>
        internal static string lbyes_smoked {
            get {
                return ResourceManager.GetString("lbyes_smoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am smoking.
        /// </summary>
        internal static string lbyes_smoking {
            get {
                return ResourceManager.GetString("lbyes_smoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string manage {
            get {
                return ResourceManager.GetString("manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As you may know that the health data herein are highly confidential and only for your reference. please be aware on printing and sending, &lt;/br&gt;do not publish this information to non-relevant..
        /// </summary>
        internal static string message_form1 {
            get {
                return ResourceManager.GetString("message_form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string minute_risk_factor {
            get {
                return ResourceManager.GetString("minute_risk_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have workplace environmental monitoring?.
        /// </summary>
        internal static string monitoringenvironment {
            get {
                return ResourceManager.GetString("monitoringenvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace environmental monitoring results.
        /// </summary>
        internal static string monitoring_results {
            get {
                return ResourceManager.GetString("monitoring_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and Surname.
        /// </summary>
        internal static string name_surname {
            get {
                return ResourceManager.GetString("name_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not approve.
        /// </summary>
        internal static string notapprove {
            get {
                return ResourceManager.GetString("notapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Comply.
        /// </summary>
        internal static string not_comply {
            get {
                return ResourceManager.GetString("not_comply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Repeated Health Check.
        /// </summary>
        internal static string not_repeat_health_check {
            get {
                return ResourceManager.GetString("not_repeat_health_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Repeated Health Check.
        /// </summary>
        internal static string no_repeat_health_check {
            get {
                return ResourceManager.GetString("no_repeat_health_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check Report.
        /// </summary>
        internal static string occupational_health_form {
            get {
                return ResourceManager.GetString("occupational_health_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check Report due to Risk Factor Related Work.
        /// </summary>
        internal static string occupational_health_report {
            get {
                return ResourceManager.GetString("occupational_health_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string postion {
            get {
                return ResourceManager.GetString("postion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Rehabilitation Action.
        /// </summary>
        internal static string process_action_form {
            get {
                return ResourceManager.GetString("process_action_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string reason_not_approve {
            get {
                return ResourceManager.GetString("reason_not_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string remark {
            get {
                return ResourceManager.GetString("remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated Health Check.
        /// </summary>
        internal static string repeat_health_check {
            get {
                return ResourceManager.GetString("repeat_health_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Report.
        /// </summary>
        internal static string report_date {
            get {
                return ResourceManager.GetString("report_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As you may know that the health data herein are highly confidential and only for your reference. please be aware on printing and sending, do not publish this information to non-relevant..
        /// </summary>
        internal static string report_message_form1 {
            get {
                return ResourceManager.GetString("report_message_form1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider for approval.
        /// </summary>
        internal static string request_approve {
            get {
                return ResourceManager.GetString("request_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible person.
        /// </summary>
        internal static string responsible_person {
            get {
                return ResourceManager.GetString("responsible_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of Environmental Inspection.
        /// </summary>
        internal static string result_risk_factor {
            get {
                return ResourceManager.GetString("result_risk_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Factor Related Work.
        /// </summary>
        internal static string risk_factor_relate_work {
            get {
                return ResourceManager.GetString("risk_factor_relate_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Factor Related Work.
        /// </summary>
        internal static string risk_factor_relate_work_form {
            get {
                return ResourceManager.GetString("risk_factor_relate_work_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string risk_factor_relate_work_other {
            get {
                return ResourceManager.GetString("risk_factor_relate_work_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal audiogram field is reqired..
        /// </summary>
        internal static string rqabnormalaudiogram {
            get {
                return ResourceManager.GetString("rqabnormalaudiogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal pulmonary function field is reqired..
        /// </summary>
        internal static string rqabnormal_pulmonary_function {
            get {
                return ResourceManager.GetString("rqabnormal_pulmonary_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action field is reqired..
        /// </summary>
        internal static string rqaction {
            get {
                return ResourceManager.GetString("rqaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age field is reqired..
        /// </summary>
        internal static string rqage {
            get {
                return ResourceManager.GetString("rqage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid age..
        /// </summary>
        internal static string rqcheckage {
            get {
                return ResourceManager.GetString("rqcheckage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hour..
        /// </summary>
        internal static string rqcheckhourriskfactor {
            get {
                return ResourceManager.GetString("rqcheckhourriskfactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid minute..
        /// </summary>
        internal static string rqcheckminuteriskfactor {
            get {
                return ResourceManager.GetString("rqcheckminuteriskfactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other field is reqired..
        /// </summary>
        internal static string rqcheckotherriskfactor {
            get {
                return ResourceManager.GetString("rqcheckotherriskfactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid service year..
        /// </summary>
        internal static string rqcheckservice_year {
            get {
                return ResourceManager.GetString("rqcheckservice_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid service year in current position..
        /// </summary>
        internal static string rqcheckservice_year_current {
            get {
                return ResourceManager.GetString("rqcheckservice_year_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal health problem or chronic diseases in the ear  field is reqired..
        /// </summary>
        internal static string rqchronic_diseases_ear {
            get {
                return ResourceManager.GetString("rqchronic_diseases_ear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company field is reqired..
        /// </summary>
        internal static string rqcompany {
            get {
                return ResourceManager.GetString("rqcompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth field is reqired..
        /// </summary>
        internal static string rqdateofbirth {
            get {
                return ResourceManager.GetString("rqdateofbirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant/Department field is reqired..
        /// </summary>
        internal static string rqdepartment {
            get {
                return ResourceManager.GetString("rqdepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date field is reqired..
        /// </summary>
        internal static string rqduedate {
            get {
                return ResourceManager.GetString("rqduedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duedate more than date now..
        /// </summary>
        internal static string rqduedate2 {
            get {
                return ResourceManager.GetString("rqduedate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of Risk Exposure per Day field is reqired..
        /// </summary>
        internal static string rqdurationriskfactor {
            get {
                return ResourceManager.GetString("rqdurationriskfactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID field is reqired..
        /// </summary>
        internal static string rqemployeeid {
            get {
                return ResourceManager.GetString("rqemployeeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach file repeated health check.
        /// </summary>
        internal static string rqfilerepeatehealthcheck {
            get {
                return ResourceManager.GetString("rqfilerepeatehealthcheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach file health check attachment.
        /// </summary>
        internal static string rqfileresulthealthcheck {
            get {
                return ResourceManager.GetString("rqfileresulthealthcheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach file result of environmental inspection attachment..
        /// </summary>
        internal static string rqfileriskfactor {
            get {
                return ResourceManager.GetString("rqfileriskfactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach file for closing action.
        /// </summary>
        internal static string rqfile_action_close {
            get {
                return ResourceManager.GetString("rqfile_action_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach file medical opinion.
        /// </summary>
        internal static string rqfile_opinion_doctor {
            get {
                return ResourceManager.GetString("rqfile_opinion_doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach file rehabilitation plan.
        /// </summary>
        internal static string rqfile_recovery_plan {
            get {
                return ResourceManager.GetString("rqfile_recovery_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function/Business Unit field is reqired..
        /// </summary>
        internal static string rqfunction {
            get {
                return ResourceManager.GetString("rqfunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiring date field is reqired..
        /// </summary>
        internal static string rqhiringdate {
            get {
                return ResourceManager.GetString("rqhiringdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check-Up Hospital field is reqired..
        /// </summary>
        internal static string rqhospital {
            get {
                return ResourceManager.GetString("rqhospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour field is reqired..
        /// </summary>
        internal static string rqhourriskfactor {
            get {
                return ResourceManager.GetString("rqhourriskfactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Description / Machine Type field is reqired..
        /// </summary>
        internal static string rqjobtype {
            get {
                return ResourceManager.GetString("rqjobtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Description / Machine Type no more than 4000 characters..
        /// </summary>
        internal static string rqJobTypeLength {
            get {
                return ResourceManager.GetString("rqJobTypeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute field is reqired..
        /// </summary>
        internal static string rqminuteriskfactor {
            get {
                return ResourceManager.GetString("rqminuteriskfactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace environmental monitoring field is reqired..
        /// </summary>
        internal static string rqmonitoringenvironment {
            get {
                return ResourceManager.GetString("rqmonitoringenvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace environmental monitoring results field is reqired..
        /// </summary>
        internal static string rqmonitoringresults {
            get {
                return ResourceManager.GetString("rqmonitoringresults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check Report due to Risk Factor Related Work field is reqired..
        /// </summary>
        internal static string rqoccupationalhealth {
            get {
                return ResourceManager.GetString("rqoccupationalhealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status field is reqired..
        /// </summary>
        internal static string rqprocessstatus {
            get {
                return ResourceManager.GetString("rqprocessstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated Health Check Attachment is reqired..
        /// </summary>
        internal static string rqrepeatehealthcheck {
            get {
                return ResourceManager.GetString("rqrepeatehealthcheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible person field is reqired..
        /// </summary>
        internal static string rqresponsible_person {
            get {
                return ResourceManager.GetString("rqresponsible_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of Environmental Inspection field is reqired..
        /// </summary>
        internal static string rqresultriskfactor {
            get {
                return ResourceManager.GetString("rqresultriskfactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Factor Related Work field is reqired..
        /// </summary>
        internal static string rqriskfactorrelatework {
            get {
                return ResourceManager.GetString("rqriskfactorrelatework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service year field is reqired..
        /// </summary>
        internal static string rqserviceyear {
            get {
                return ResourceManager.GetString("rqserviceyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Year in Current Position field is reqired..
        /// </summary>
        internal static string rqserviceyearcurrent {
            get {
                return ResourceManager.GetString("rqserviceyearcurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significant risk factor related work or Insignificant risk factor related work is reqired..
        /// </summary>
        internal static string rqsignificantorinsignificant {
            get {
                return ResourceManager.GetString("rqsignificantorinsignificant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoked a cigarettes field is reqired..
        /// </summary>
        internal static string rqsmoked_cigarettes {
            get {
                return ResourceManager.GetString("rqsmoked_cigarettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify field is reqired..
        /// </summary>
        internal static string rqspecify_chronic_diseases_ear {
            get {
                return ResourceManager.GetString("rqspecify_chronic_diseases_ear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearing threshold level field is reqired..
        /// </summary>
        internal static string rqthearing_threshold_level {
            get {
                return ResourceManager.GetString("rqthearing_threshold_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Control field is reqired..
        /// </summary>
        internal static string rqtypecontrol {
            get {
                return ResourceManager.GetString("rqtypecontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year field is reqired..
        /// </summary>
        internal static string rqyear {
            get {
                return ResourceManager.GetString("rqyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of Environmental Inspection field is reqired..
        /// </summary>
        internal static string rqyearriskfactor {
            get {
                return ResourceManager.GetString("rqyearriskfactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show file.
        /// </summary>
        internal static string showfile {
            get {
                return ResourceManager.GetString("showfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significant risk factor related work.
        /// </summary>
        internal static string significant {
            get {
                return ResourceManager.GetString("significant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significant risk factor related work or Insignificant risk factor related work.
        /// </summary>
        internal static string significantorinsignificant {
            get {
                return ResourceManager.GetString("significantorinsignificant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Control.
        /// </summary>
        internal static string typecontrol {
            get {
                return ResourceManager.GetString("typecontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of Environmental Inspection.
        /// </summary>
        internal static string year_risk_factor_relate_work {
            get {
                return ResourceManager.GetString("year_risk_factor_relate_work", resourceCulture);
            }
        }
    }
}
