//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select company,function,department,division and section..
        /// </summary>
        internal static string alertselectarea {
            get {
                return ResourceManager.GetString("alertselectarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area All.
        /// </summary>
        internal static string areaall {
            get {
                return ResourceManager.GetString("areaall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Manager.
        /// </summary>
        internal static string areamanager {
            get {
                return ResourceManager.GetString("areamanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area name.
        /// </summary>
        internal static string areaname {
            get {
                return ResourceManager.GetString("areaname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area OH&amp;S.
        /// </summary>
        internal static string areaohs {
            get {
                return ResourceManager.GetString("areaohs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Supervisor.
        /// </summary>
        internal static string areasupervisor {
            get {
                return ResourceManager.GetString("areasupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btadd {
            get {
                return ResourceManager.GetString("btadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btCancel {
            get {
                return ResourceManager.GetString("btCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btClose {
            get {
                return ResourceManager.GetString("btClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string btconfirm {
            get {
                return ResourceManager.GetString("btconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm and Investigate.
        /// </summary>
        internal static string btConfirmandInvestigate {
            get {
                return ResourceManager.GetString("btConfirmandInvestigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string btdownload {
            get {
                return ResourceManager.GetString("btdownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel.
        /// </summary>
        internal static string btExport {
            get {
                return ResourceManager.GetString("btExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PDF.
        /// </summary>
        internal static string btExportpdf {
            get {
                return ResourceManager.GetString("btExportpdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btLoginCheck {
            get {
                return ResourceManager.GetString("btLoginCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify case.
        /// </summary>
        internal static string btLoginContractor {
            get {
                return ResourceManager.GetString("btLoginContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify case.
        /// </summary>
        internal static string btLoginNotify {
            get {
                return ResourceManager.GetString("btLoginNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string btLogout {
            get {
                return ResourceManager.GetString("btLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btOK {
            get {
                return ResourceManager.GetString("btOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btOK2 {
            get {
                return ResourceManager.GetString("btOK2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen.
        /// </summary>
        internal static string btReopen {
            get {
                return ResourceManager.GetString("btReopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btsave {
            get {
                return ResourceManager.GetString("btsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Management.
        /// </summary>
        internal static string btSideBarAreaManagement {
            get {
                return ResourceManager.GetString("btSideBarAreaManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard.
        /// </summary>
        internal static string btSideBarDashboardHazard {
            get {
                return ResourceManager.GetString("btSideBarDashboardHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident.
        /// </summary>
        internal static string btSideBarDashboardIncident {
            get {
                return ResourceManager.GetString("btSideBarDashboardIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VFL.
        /// </summary>
        internal static string btSideBarDashboardSot {
            get {
                return ResourceManager.GetString("btSideBarDashboardSot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        internal static string btSideBarHoliday {
            get {
                return ResourceManager.GetString("btSideBarHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard.
        /// </summary>
        internal static string btSideBarMyActionHazard {
            get {
                return ResourceManager.GetString("btSideBarMyActionHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident.
        /// </summary>
        internal static string btSideBarMyActionIncident {
            get {
                return ResourceManager.GetString("btSideBarMyActionIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VFL.
        /// </summary>
        internal static string btSideBarMyActionSot {
            get {
                return ResourceManager.GetString("btSideBarMyActionSot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Group.
        /// </summary>
        internal static string btSideBarNotifyGroup {
            get {
                return ResourceManager.GetString("btSideBarNotifyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string btSideBarSetting {
            get {
                return ResourceManager.GetString("btSideBarSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin.
        /// </summary>
        internal static string btSideBarSuperAdmin {
            get {
                return ResourceManager.GetString("btSideBarSuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string btSideBarTarget {
            get {
                return ResourceManager.GetString("btSideBarTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work and Training Hour.
        /// </summary>
        internal static string btSideBarWorkHour {
            get {
                return ResourceManager.GetString("btSideBarWorkHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string btSubmit {
            get {
                return ResourceManager.GetString("btSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Report.
        /// </summary>
        internal static string btSubmitReport {
            get {
                return ResourceManager.GetString("btSubmitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close all action.
        /// </summary>
        internal static string close_all_action {
            get {
                return ResourceManager.GetString("close_all_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this action?.
        /// </summary>
        internal static string confirm_cancel_action {
            get {
                return ResourceManager.GetString("confirm_cancel_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this action?.
        /// </summary>
        internal static string confirm_close_action {
            get {
                return ResourceManager.GetString("confirm_close_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to request close this action?.
        /// </summary>
        internal static string confirm_request_close_action {
            get {
                return ResourceManager.GetString("confirm_request_close_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach file before submit..
        /// </summary>
        internal static string confirm_upload_image_action {
            get {
                return ResourceManager.GetString("confirm_upload_image_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc no..
        /// </summary>
        internal static string doc_no {
            get {
                return ResourceManager.GetString("doc_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID of reporter.
        /// </summary>
        internal static string employee_reporter {
            get {
                return ResourceManager.GetString("employee_reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Login!Please enter the correct user name and password or contact Service Desk if you could not access the system.
        /// </summary>
        internal static string errorCheck {
            get {
                return ResourceManager.GetString("errorCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Login!Please enter the correct email address or contact your area safety officer if you could not access the system.
        /// </summary>
        internal static string errorContractor {
            get {
                return ResourceManager.GetString("errorContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Login!Please enter the correct employee ID and First name or contact P&amp;OP to check your ID or contact Service Desk if you could not access the system.
        /// </summary>
        internal static string errorNotify {
            get {
                return ResourceManager.GetString("errorNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to login with Employee ID, Please use Computer ID tab.
        /// </summary>
        internal static string force_login_ad {
            get {
                return ResourceManager.GetString("force_login_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Func. Mgr. Health.
        /// </summary>
        internal static string functionalmanager {
            get {
                return ResourceManager.GetString("functionalmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string lbAdmin {
            get {
                return ResourceManager.GetString("lbAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard.
        /// </summary>
        internal static string lbAllHazard {
            get {
                return ResourceManager.GetString("lbAllHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health &lt;/br&gt; Rehabilitation.
        /// </summary>
        internal static string lbAllHealth {
            get {
                return ResourceManager.GetString("lbAllHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident.
        /// </summary>
        internal static string lbAllIncident {
            get {
                return ResourceManager.GetString("lbAllIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All VFL.
        /// </summary>
        internal static string lbAllSot {
            get {
                return ResourceManager.GetString("lbAllSot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string lbArea {
            get {
                return ResourceManager.GetString("lbArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Manager.
        /// </summary>
        internal static string lbareamanager {
            get {
                return ResourceManager.GetString("lbareamanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area OH&amp;S.
        /// </summary>
        internal static string lbareaohs {
            get {
                return ResourceManager.GetString("lbareaohs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Supervisor.
        /// </summary>
        internal static string lbareasupervisor {
            get {
                return ResourceManager.GetString("lbareasupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        internal static string lbContractor {
            get {
                return ResourceManager.GetString("lbContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lbcountry {
            get {
                return ResourceManager.GetString("lbcountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string lbDashboard {
            get {
                return ResourceManager.GetString("lbDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of close.
        /// </summary>
        internal static string lbdateclose {
            get {
                return ResourceManager.GetString("lbdateclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string lbDepartment {
            get {
                return ResourceManager.GetString("lbDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department (Area OH&amp;S).
        /// </summary>
        internal static string lbdepartment_area {
            get {
                return ResourceManager.GetString("lbdepartment_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Manager (Health Rehab).
        /// </summary>
        internal static string lbdepartment_functional_area {
            get {
                return ResourceManager.GetString("lbdepartment_functional_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string lbDivision {
            get {
                return ResourceManager.GetString("lbDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division (Area Manager).
        /// </summary>
        internal static string lbdivision_area {
            get {
                return ResourceManager.GetString("lbdivision_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date is reqired..
        /// </summary>
        internal static string lbenddate {
            get {
                return ResourceManager.GetString("lbenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard Report.
        /// </summary>
        internal static string lbHazardExport {
            get {
                return ResourceManager.GetString("lbHazardExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Rehabilitation Report.
        /// </summary>
        internal static string lbHealthExport {
            get {
                return ResourceManager.GetString("lbHealthExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate OH&amp;S Admin.
        /// </summary>
        internal static string lbHederDelegateOHS {
            get {
                return ResourceManager.GetString("lbHederDelegateOHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate Super Admin.
        /// </summary>
        internal static string lbHederDelegateSuperadmin {
            get {
                return ResourceManager.GetString("lbHederDelegateSuperadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OH&amp;S Admin.
        /// </summary>
        internal static string lbHederOHS {
            get {
                return ResourceManager.GetString("lbHederOHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Admin.
        /// </summary>
        internal static string lbHederSuperadmin {
            get {
                return ResourceManager.GetString("lbHederSuperadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lbHome {
            get {
                return ResourceManager.GetString("lbHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Report.
        /// </summary>
        internal static string lbIncidentExport {
            get {
                return ResourceManager.GetString("lbIncidentExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on bar graph for more detail.
        /// </summary>
        internal static string lbinfodashboard {
            get {
                return ResourceManager.GetString("lbinfodashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Action.
        /// </summary>
        internal static string lbMyAction {
            get {
                return ResourceManager.GetString("lbMyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lbNameEnArea {
            get {
                return ResourceManager.GetString("lbNameEnArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        internal static string lbNameThArea {
            get {
                return ResourceManager.GetString("lbNameThArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string lbReport {
            get {
                return ResourceManager.GetString("lbReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report &lt;/br&gt; Hazard.
        /// </summary>
        internal static string lbReportHazard {
            get {
                return ResourceManager.GetString("lbReportHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report &lt;/br&gt; Health Rehab..
        /// </summary>
        internal static string lbReportHealth {
            get {
                return ResourceManager.GetString("lbReportHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report &lt;/br&gt;Accident /Near Miss.
        /// </summary>
        internal static string lbReportIncident {
            get {
                return ResourceManager.GetString("lbReportIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report &lt;/br&gt; VFL.
        /// </summary>
        internal static string lbReportSot {
            get {
                return ResourceManager.GetString("lbReportSot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Factor Related Work and Health Check Report is reqired..
        /// </summary>
        internal static string lbrqtalberiskandoccu {
            get {
                return ResourceManager.GetString("lbrqtalberiskandoccu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string lbSection {
            get {
                return ResourceManager.GetString("lbSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section (Area Supervisor).
        /// </summary>
        internal static string lbsection_area {
            get {
                return ResourceManager.GetString("lbsection_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is reqired..
        /// </summary>
        internal static string lbstartdate {
            get {
                return ResourceManager.GetString("lbstartdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        internal static string lbtypereport {
            get {
                return ResourceManager.GetString("lbtypereport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Case By Employee.
        /// </summary>
        internal static string listTab1 {
            get {
                return ResourceManager.GetString("listTab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Case By Contractor.
        /// </summary>
        internal static string listTab2 {
            get {
                return ResourceManager.GetString("listTab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer ID.
        /// </summary>
        internal static string listTab3 {
            get {
                return ResourceManager.GetString("listTab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string manage {
            get {
                return ResourceManager.GetString("manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard.
        /// </summary>
        internal static string menubarAllHazard {
            get {
                return ResourceManager.GetString("menubarAllHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Rehabilitation.
        /// </summary>
        internal static string menubarAllHealth {
            get {
                return ResourceManager.GetString("menubarAllHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident.
        /// </summary>
        internal static string menubarAllIncident {
            get {
                return ResourceManager.GetString("menubarAllIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All SOT.
        /// </summary>
        internal static string menubarAllSot {
            get {
                return ResourceManager.GetString("menubarAllSot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permision.
        /// </summary>
        internal static string nopermission {
            get {
                return ResourceManager.GetString("nopermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach file before close action..
        /// </summary>
        internal static string require_attach_file {
            get {
                return ResourceManager.GetString("require_attach_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name English no more than 50 characters..
        /// </summary>
        internal static string rqNameEnArea {
            get {
                return ResourceManager.GetString("rqNameEnArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Thai no more than 50 characters..
        /// </summary>
        internal static string rqNameThArea {
            get {
                return ResourceManager.GetString("rqNameThArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select division and section or select other when you do not..
        /// </summary>
        internal static string select_division_section {
            get {
                return ResourceManager.GetString("select_division_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string sEmptyTable {
            get {
                return ResourceManager.GetString("sEmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string sFirst {
            get {
                return ResourceManager.GetString("sFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view _START_ - _END_ of _TOTAL_.
        /// </summary>
        internal static string sInfo {
            get {
                return ResourceManager.GetString("sInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 to 0 of 0.
        /// </summary>
        internal static string sInfoEmpty {
            get {
                return ResourceManager.GetString("sInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtering from _MAX_ records).
        /// </summary>
        internal static string sInfoFiltered {
            get {
                return ResourceManager.GetString("sInfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string sLast {
            get {
                return ResourceManager.GetString("sLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display _MENU_ records.
        /// </summary>
        internal static string sLengthMenu {
            get {
                return ResourceManager.GetString("sLengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string sLoadingRecords {
            get {
                return ResourceManager.GetString("sLoadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string sNext {
            get {
                return ResourceManager.GetString("sNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string sPrevious {
            get {
                return ResourceManager.GetString("sPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string sProcessing {
            get {
                return ResourceManager.GetString("sProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string sSearch {
            get {
                return ResourceManager.GetString("sSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Data.
        /// </summary>
        internal static string sZeroRecords {
            get {
                return ResourceManager.GetString("sZeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create action.
        /// </summary>
        internal static string take_action {
            get {
                return ResourceManager.GetString("take_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string txtEmailRegister {
            get {
                return ResourceManager.GetString("txtEmailRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string txtFirstnameNotify {
            get {
                return ResourceManager.GetString("txtFirstnameNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string txtPasswordCheck {
            get {
                return ResourceManager.GetString("txtPasswordCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer ID.
        /// </summary>
        internal static string txtUsernameCheck {
            get {
                return ResourceManager.GetString("txtUsernameCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        internal static string txtUserNotify {
            get {
                return ResourceManager.GetString("txtUserNotify", resourceCulture);
            }
        }
    }
}
