//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Setting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Setting", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string lbOther {
            get {
                return ResourceManager.GetString("lbOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Part.
        /// </summary>
        internal static string LinkBodyPart {
            get {
                return ResourceManager.GetString("LinkBodyPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event or exposure.
        /// </summary>
        internal static string LinkEventOrExposure {
            get {
                return ResourceManager.GetString("LinkEventOrExposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPE.
        /// </summary>
        internal static string LinkFPE {
            get {
                return ResourceManager.GetString("LinkFPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital.
        /// </summary>
        internal static string LinkHospital {
            get {
                return ResourceManager.GetString("LinkHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature of injury.
        /// </summary>
        internal static string LinkNatureOfInjury {
            get {
                return ResourceManager.GetString("LinkNatureOfInjury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupational Health Report.
        /// </summary>
        internal static string LinkOccupationalHealthWork {
            get {
                return ResourceManager.GetString("LinkOccupationalHealthWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Factor Related to Work.
        /// </summary>
        internal static string LinkRiskFactorRelateToWork {
            get {
                return ResourceManager.GetString("LinkRiskFactorRelateToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity of injury.
        /// </summary>
        internal static string LinkSeverityOfInjury {
            get {
                return ResourceManager.GetString("LinkSeverityOfInjury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category of hazard.
        /// </summary>
        internal static string LinkSourceOfHazard {
            get {
                return ResourceManager.GetString("LinkSourceOfHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source of incident.
        /// </summary>
        internal static string LinkSourceOfIncident {
            get {
                return ResourceManager.GetString("LinkSourceOfIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Control.
        /// </summary>
        internal static string LinkTypeOfControl {
            get {
                return ResourceManager.GetString("LinkTypeOfControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of employee.
        /// </summary>
        internal static string LinkTypeOfEmployee {
            get {
                return ResourceManager.GetString("LinkTypeOfEmployee", resourceCulture);
            }
        }
    }
}
